sonar.projectKey=ogiboy_home-media-portal
sonar.organization=ogiboy
sonar.sources=.
sonar.scm.provider=git
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.e1.resourceKey=**/app/globals.css
